### ISSUE TITLE
Node V17+ not supported for the Redux Fundamentals Example App

### ISSUE THREAD

**Issue by MJADangcil** [reduxjs/redux-fundamentals-example-app#11]
Following the commands (`npm install` and `npm start`) from the [React Redux Tutorial](https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers) I receive this error message:

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/.../redux-fundamentals-example-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/.../redux-fundamentals-example-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at /.../redux-fundamentals-example-app/node_modules/webpack/lib/NormalModule.js:452:10
    at /.../redux-fundamentals-example-app/node_modules/webpack/lib/NormalModule.js:323:13
    at /.../redux-fundamentals-example-app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /.../redux-fundamentals-example-app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/.../redux-fundamentals-example-app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /.../redux-fundamentals-example-app/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

Installed version of Node:
```
user@user redux-fundamentals-example-app % node --version
v21.6.1
```

**Comment by markerikson** [comment]
Known issue. I've already updated the "Redux Essentials" tutorial example app to use Vite and work on Node 18+, but haven't had time to update the "Fundamentals", and realistically it won't get updated until the "Essentials" tutorial revamp is done.

Simplest fix on the user end is probably to update `react-scripts` to version 5, as that updates the Webpack version.

**Comment by MJADangcil** [comment]
Gotcha, thanks for the quick update! That makes sense, the "Fundamentals" tutorial is a bit outdated.

I've gotten to work with my Node version by changing the npm start and build scripts--just figured I'd report on my end.
```
"scripts": {
    "start": "export SET NODE_OPTIONS=--openssl-legacy-provider && react-scripts start",
    "build": "export SET NODE_OPTIONS=--openssl-legacy-provider && react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
```

**Comment by markerikson** [comment]
Yeah, both tutorials were written in 2020, and used CRA4.

I've already revamped the "Essentials" tutorial to use Vite with the existing JS code, and am working on a full TS conversion of that "Essentials" example.

Unfortunately, updating the app to use Vite also seems to have forced CodeSandbox to alter how it's doing the sandbox previews.  I tagged the CSB devs, but things still seem to be off from how they were before, and I don't want to mess with the "Fundamentals" setup until that's figured out.

**Comment by MJADangcil** [comment]
Fair enough. Well, feel free to update this issue as you see fit--I'm fine with my fix moving forward.
